### PR TITLE
Total refactoring and a few new features

### PR DESCRIPTION
**Pull request by EvilFreelancer**
Hello @Chocobozzz !
We previously discussed about refactoring, so I had a couple of free hours and I did it.
The list of changes is very large, but the core of the system works the same as before.
This updates will further simplify the process of creating the Docker image.

* Total refactoring of project
  * Originally everything was in the same directory, but I created the `public` directory and put `index.php` here. This should improve the security of the system.
  * Scripts moved to `scripts`, js/css/img into the `resources`
  * `include` directory is left on the same place
* dotEnv file added as global configuration file of the system
  * Almost all veriables moved to dotEnv file
  * `install-openvpn.sh` worked with parameters from this file
* Composer added (for dotEnv plugin support from php)
  * In `index.php` added the dorEnv initialization line (probably may be problems with older PHP versions below 5.6)
* Bower removed, css/js packages now available via npm
* Images, styles, scripts moved to separated directory
* Gulp is added instead of bower, now it prepares the project (starts automatically after npm install)
  * From img/js/css gulp copies everything in the appropriate directory
  * From `node_modules` gulp copies only what need (js/css/fonts)
* Paths of OpenVPN logs was changes to `/var/log/openvpn/` folder (it may be required for docker)

## Small how to

* cp .env.example .env
* npm install
* composer install

After this need fix your root path in web-server's config (need to add public)

### TODO (probably in next PR)
* Rewrite `installation/scripts` to php - this will help to implement any required functionality on php, using the global configuration
* Set the static path of `installation/scripts` - in order not to write twice the system settings, but to use the global configuration
* Add LDAP support - need to add variabled into the dotEnv, web-interface and into the login script
* Remove "Install MySQL" part, IMHO better write simple migrations
* etc.

### P.S.
Some features may not work, for example `install.sh` because paths was changed.
If "da way" in my PR is okay for you, I can fix any other remaining problems (for example, with paths).

### CODE REVIEW

**Comment by Chocobozzz** [comment]
I like it!

I merging it in a WIP branch :)

**Comment by EvilFreelancer** [comment]
@Chocobozzz cool, then need to continue my way, because not all ideas is implemented.
(Btw, maybe in the future it is worth creating a dev branch or 0.4-dev?)

I understood how your system is works (after a couple of cups of coffee :) idea is a very cool and simple, mysql database with logs and users, auth scripts (work via mysql) for openvpn login/connect/disconnect and simple web interface (and complex of scripts of course).

Without going into details, the system consists of three components.

**Comment by SansPseudoFix** [comment]
> Rewrite installation/scripts to php - this will help to implement any required functionality on php, using the global configuration

Oh nooo…! I will definitely be useless if you do that :(

@Chocobozzz stop him!

And seriously: nice job @EvilFreelancer  :)

**Comment by EvilFreelancer** [comment]
> Oh nooo…! I will definitely be useless if you do that :(

@SansPseudoFix lol why? logic not will change and what difference which language will be used? I like the PHP version because the DotEnv class is very convenient and simple. Will be possible to use a same one global configuration for the entire project (web app, auth scripts, install stage etc).

But I know, you're probably more worried about performance, this is a good point, will need compare the speed and memory usage of both variants.

**Pull request merged**
