### PR TITLE
Added basic LDAP connection in login.sh

### PR DESCRIPTION
**Pull request by driesp**
I created a basic LDAP connection in the login.sh file. This can both be used in both AD as LDAP environments. Still other additions for this feature to come...

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Awesome!

I keep this PR opened as WIP.

**Comment by driesp** [comment]
Thanks man. To be honest i'm not really good with frontends. Is there a way that you can help me implement that in your app?

**Comment by Chocobozzz** [comment]
You mean the LDAP user table on the admin page?

**Comment by driesp** [comment]
Yes indeed.

**Comment by SansPseudoFix** [comment]
I will take a look to frontend (maybe Friday).
Ping @nikaro who seemed to be interested by this implementation #14

**Comment by nikaro** [comment]
Yep sorry i did not had time to work on this, and i will not have soon either… But if i can help i will.

This said, i think `USELDAP` in `config.sh` should be at 0 by default.

And it would be even better if we could choose to use TLS for LDAP operations :smiley:

**Comment by driesp** [comment]
@nikaro. I will have a look into the TLS part. But I think that would be possible. Othere requests ?

**Comment by nikaro** [comment]
I see nothing to add for the moment :-)

**Comment by Chocobozzz** [comment]
I merged your work in the ldap branch as WIP :)

**Pull request merged**
