### PR TITLE
Add installation command lines for debian jessie

### PR DESCRIPTION
**Pull request by SansPseudoFix**
Works with native debian nodejs version ``0.10.29~dfsg-2``.

### CODE REVIEW

**Comment by driesp** [comment]
Look at te dependencie installer in my branch, autodetects the operating system.

**Comment by SansPseudoFix** [comment]
I don't get it. What you mean? What is your OS?

**Comment by driesp** [comment]
It's for all linux distro's. It gets a string with the OS name and version. It helps you determine which commandos you need to use. Eg Ubuntu vs CentOs

**Comment by SansPseudoFix** [comment]
> Look at te dependencie installer in my branch

Actually, we can't see any of your branchs. Private repo?

**Pull request merged**
