### PR TITLE
EasyRSA 3.x + Refactoring

### PR DESCRIPTION
**Pull request by nikaro**
Updated to use EasyRSA 3.x and with @SansPseudoFix pull request https://github.com/Chocobozzz/OpenVPN-Admin/pull/9 with some changes (explained in commits).

### CODE REVIEW

**Comment by Chocobozzz** [comment]
Hi @nikaro thanks a lot for the PR.

Could you rebase from the dev branch and squash your commits?

**Comment by nikaro** [comment]
It's done :smiley:

**Comment by Chocobozzz** [comment]
Thanks @nikaro :)

But can you make only one commit: "upgrade EasyRSA to 3.x"?  Because your PR contains 14 commits which is not very readable.

Here you can find a small guide: https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit

**Comment by nikaro** [comment]
I'll try to do it tomorrow :-)

**Comment by nikaro** [comment]
I'm closing this pull request in favor of https://github.com/Chocobozzz/OpenVPN-Admin/pull/15

**Pull request closed without merging**
