### PR TITLE
a bug about "Enabled" option

### PR DESCRIPTION
**Pull request by QingfengLee**
1. Fix a bug about the user enable box. It can not be  enable when i disable a user.
2. Add a configuration option about "explicit-exit-notify"

### CODE REVIEW

**Comment by GiannisRallis** [comment]
Worked perfect fom me!! Thank you!!

**Comment by QingfengLee** [comment]
I didn't notice it at first, but I received an email about it. I repeated it in Chrome. Maybe someone else has the same problem.

**Comment by GiannisRallis** [comment]
> I didn't notice it at first, but I received an email about it. I repeated it in Chrome. Maybe someone else has the same problem.

It was my on e-mail

**Comment by Chocobozzz** [comment]
Thanks

**Pull request merged**
